mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/hospital?useSSL=false&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: cwb



